runtime: custom
env: flex
# Scaling Options help to avoid going overbudget on a project.
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

#Makes sure youre not serving an empty site
liveness_check:
  path: "/"
  check_interval_sec: 120
  failure_threshold: 3


readiness_check:
  path: "/"
  app_start_timeout_sec: 30

#gives recource constraints per machine
resources:
  cpu: 1
  memory_gb: 0.5