options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      - clone
      - https://github.com/Sammystar075/kindle-suite.git
      - /workspace/kindle-suite

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/ca-1-10589529-2/docker-repo/nginx-alpine-simple:latest',
        '.'
      ]
    dir: /workspace/kindle-suite

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/ca-1-10589529-2/docker-repo/nginx-alpine-simple:latest'
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'markdown-editor',
        '--image', 'us-central1-docker.pkg.dev/ca-1-10589529-2/docker-repo/nginx-alpine-simple:latest',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--port', '8080',
        '--service-account', 'bob-le-builder@ca-1-10589529-2.iam.gserviceaccount.com'
      ]

images:
  - 'us-central1-docker.pkg.dev/ca-1-10589529-2/docker-repo/nginx-alpine-simple:latest'
