options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1️⃣ Clone website repo
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/Sammystar075/kindle-suite.git
      - website

  # 2️⃣ Build nginx image using cloned files
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/ca-1-10589529-2/docker-repo/nginx-site:latest",
        "."
      ]

  # 3️⃣ Push image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/ca-1-10589529-2/docker-repo/nginx-site:latest"
      ]

  # 4️⃣ Deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run", "deploy", "nginx-site",
        "--image", "us-central1-docker.pkg.dev/ca-1-10589529-2/docker-repo/nginx-site:latest",
        "--platform", "managed",
        "--region", "us-central1",
        "--allow-unauthenticated",
        "--port", "8080"
      ]

images:
  - us-central1-docker.pkg.dev/ca-1-10589529-2/docker-repo/nginx-site:latest
